language: ruby
before_script:
  - "mysql -e 'create database goldencobra_test;'"
bundler_args: --without development
before_script:
  - "script: bundle exec gem install activerecord-mysql2-adapter"
  - "script: bundle exec rails g goldencobra:install"
  - "script: bundle exec rake db:migrate db:test:prepare"
  - "script: bundle exec rake"
rvm:
  - 1.9.2
gemfile:
  - Gemfile
branches:
  only:
    - master
mysql:
  adapter: mysql2
  database: goldencobra_test
  username: root
  encoding: utf8
