language: ruby
before_script:
  - "mysql -e 'create database goldencobra_test;'"
bundler_args: --without development
rvm:
  - 1.9.2
gemfile:
  - Gemfile
branches:
  only:
    - master
script: bundle exec rake
mysql:
  adapter: mysql2
  database: goldencobra_test
  username: root
  encoding: utf8
