goldencobra:
    page:
        default_title_tag: "Goldencobra"
    article:
        article_index:
            link_to_article: "weiterlesen"
    url: "www.goldencobra.de"
    facebook:
        appid: "123456"
